//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISO605_WindowsForms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class candidato
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public candidato()
        {
            this.empleadoes = new HashSet<empleado>();
            this.capacitacions = new HashSet<capacitacion>();
            this.competencias = new HashSet<competencia>();
            this.experiencia_laboral = new HashSet<experiencia_laboral>();
            this.idiomas = new HashSet<idioma>();
        }
    
        public System.Guid candidato_id { get; set; }
        public string cedula { get; set; }
        public string nombre { get; set; }
        public System.Guid posicion_aspira { get; set; }
        public Nullable<decimal> salario_aspira { get; set; }
        public Nullable<System.Guid> empleado_recomienda { get; set; }
    
        public virtual empleado empleado { get; set; }
        public virtual posicion posicion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<empleado> empleadoes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<capacitacion> capacitacions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<competencia> competencias { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<experiencia_laboral> experiencia_laboral { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<idioma> idiomas { get; set; }
    }
}
