//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISO605_WindowsForms.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class capacitacion
    {
        public System.Guid capacitaciones_id { get; set; }
        public string descripcion { get; set; }
        public Nullable<System.Guid> nivel { get; set; }
        public Nullable<System.DateTime> fecha_desde { get; set; }
        public Nullable<System.DateTime> fecha_hasta { get; set; }
        public string nombre_institucion { get; set; }
        public System.Guid candidato_id { get; set; }
    
        public virtual candidato candidato { get; set; }
    }
}
