//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ISO605_WindowsForms.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ISO605Entities : DbContext
    {
        public ISO605Entities()
            : base("name=ISO605Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<candidato> candidatoes { get; set; }
        public virtual DbSet<capacitacion> capacitacions { get; set; }
        public virtual DbSet<competencia> competencias { get; set; }
        public virtual DbSet<departamento> departamentoes { get; set; }
        public virtual DbSet<empleado> empleadoes { get; set; }
        public virtual DbSet<experiencia_laboral> experiencia_laboral { get; set; }
        public virtual DbSet<idioma> idiomas { get; set; }
        public virtual DbSet<posicion> posicions { get; set; }
    }
}
